trigger:
  - main

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "70193de8-17c3-4d45-aed9-7b6d459cb210"
  imageRepository: "martinsutherlandazurepipelinedemo"
  containerRegistry: "customersapp.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"
  appName: "Azure-test-App-Two"
  azureSubscription: "Azure subscription 1 (12d4a125-7d4d-45ad-8101-2ba4e5ce1593)"
  vmImageName: "ubuntu-latest"
  uiSource: "/src"

stages:


  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Push stage
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Run
    displayName: Run stage
    jobs:
      - job: Run
        displayName: Run
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Run stage
            inputs:
              script: |
                docker run -p 3000:3000 -d --name $(containerRegistry)/$(imageRepository):$(tag)
                
      - job: test
        timeoutInMinutes: '60'
        pool:
          vmImage: "ubuntu-latest"
    
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"
    
          - script: |
              npm ci
            displayName: "Install dependencies"
    
          - script: |
              npx playwright install --with-deps
            displayName: "Install Playwright Browsers"
    
          - script: |
              npx playwright test
            displayName: "Run Playwright tests"
    
          - publish: $(System.DefaultWorkingDirectory)/playwright-report
            artifact: playwright-report
            condition: always()
  


  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: AzureWebAppContainer@1
            displayName: "Deploy stage"
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              imageName: $(containerRegistry)/$(imageRepository):$(tag)
