trigger:
  - main

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "70193de8-17c3-4d45-aed9-7b6d459cb210"
  imageRepository: "martinsutherlandazurepipelinedemo"
  containerRegistry: "customersapp.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"
  appName: "Azure-test-App-Two"
  azureSubscription: "Azure subscription 1 (12d4a125-7d4d-45ad-8101-2ba4e5ce1593)"
  vmImageName: "ubuntu-latest"
  uiSource: '/src'

stages:
  - stage: Build and Test
    displayName: Build React App
    jobs:
      - job: BuildReactApp
        timeoutInMinutes: '2'
        displayName: Build and Run React App
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              pushd $(uiSource)
              npm install
              npm run build
              npm start
              npx playwright test /tests/example.spec.ts
            displayName: "Build and Run React App"
            workingDirectory: $(Build.SourcesDirectory)

  - stage: Docker Build
    displayName: Docker Build stage
    jobs:
      - job: Build
        displayName: Docker Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Docker push
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: AzureWebAppContainer@1
            displayName: "Deploy stage"
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              imageName: $(containerRegistry)/$(imageRepository):$(tag)
